# Generated by Django 4.1.7 on 2023-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booksandauthors", "0004_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["title"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(
                to="booksandauthors.author", verbose_name="Автор"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="title",
            field=models.CharField(max_length=55, unique=True, verbose_name="Название"),
        ),
    ]
