version: '3.11'

services:
  api:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: &api-environment
      DJANGO_ENV: dev
      DJANGO_SECRET_KEY: secret_key
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    command: >
      sh -c "python manage.py migrate &&
             python manage.py make_base &&
             python manage.py init_admin &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres