version: "3.8"

x-app-config: &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: db
  DATABASE_PORT: 5432

services:
  app:
    build:
      context: .
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:14.8-alpine3.18
    environment: *db-config
    ports:
      - "5432:5432"